[tool.poetry]
name = "omid-openalex"
version = "0.1.0"
description = ""
authors = ["Elia Rizzetto <elia.rizzetto@gmail.com>"]
readme = "README.md"
packages = [{include = "omid_openalex"}]

[tool.poetry.dependencies]
python = "^3.9"
jupyter = "^1.0.0"
pandas = "^2.0.1"
tqdm = "^4.65.0"
dask = {extras = ["complete"], version = "^2023.5.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
