[tool.poetry]
name = "omid-openalex"
version = "0.1.0"
description = ""
authors = ["Elia Rizzetto <elia.rizzetto@gmail.com>"]
readme = "README.md"
packages = [{include = "omid_openalex"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
