meta_config:
  meta_inp_dir: '/path/to/meta_input_directory'
  meta_ids_out_dir: '/path/to/meta_ids_output_directory'

openalex_works:
  inp_dir: 'openalex_data'
  out_dir: 'output_openalex_ids'
  entity_type: 'work'
openalex_sources:
  inp_dir: 'openalex_data'
  out_dir: 'output_openalex_ids'
  entity_type: 'source'


## If needed, add configs for creating the tables of other OpenAlex entity types (authors, funders, publishers, institutions).
#openalex_authors:
#    inp_dir: 'openalex_data/authors'
#    out_dir: 'output_openalex_ids'
#    entity_type: 'author'
#openalex_funders:
#    inp_dir: 'openalex_data/funders'
#    out_dir: 'output_openalex_ids'
#    entity_type: 'funder'
#openalex_publishers:
#    inp_dir: 'openalex_data/publishers'
#    out_dir: 'output_openalex_ids'
#    entity_type: 'publisher'
#openalex_institutions:
#    inp_dir: 'openalex_data/institutions'
#    out_dir: 'output_openalex_ids'
#    entity_type: 'institution'


db_works_doi:
  inp_dir: 'output_openalex_ids'
  db_path: 'openalex.db'
  id_type: 'doi'
  entity_type: 'work'
db_works_pmid:
  inp_dir: 'output_openalex_ids'
  db_path: 'openalex.db'
  id_type: 'pmid'
  entity_type: 'work'
db_works_pmcid:
    inp_dir: 'output_openalex_ids'
    db_path: 'openalex.db'
    id_type: 'pmcid'
    entity_type: 'work'
db_sources_issn:
  inp_dir: 'output_openalex_ids'
  db_path: 'openalex.db'
  id_type: 'issn'
  entity_type: 'source'
db_sources_wikidata:
  inp_dir: 'output_openalex_ids'
  db_path: 'openalex.db'
  id_type: 'wikidata'
  entity_type: 'source'

## If needed, add config for other id and OpenAlex entity types (authors, funders, publishers, institutions) See example below.
#db_authors_orcid:
#    inp_dir: ''
#    db_path: 'openalex.db'
#    id_type: 'orcid'
#    entity_type: 'author'

mapping:
  inp_dir: 'input_data'
  db_path: 'openalex.db'
  out_dir: 'output_mapping'
  res_type_field: True
